package_rename_config:
  android:
    app_name: FSDA Base
    package_name: com.fdelux.fsdabase
    override_old_package: com.example.fsdabase
    lang: kotlin

  ios:
    app_name: FSDA Base
    bundle_name: fsdabase
    bundle_id: com.fdelux.fsdabase

  web:
    app_name: FSDA Base
    description: FSDA Base

  linux:
    app_name: FSDA Base
    package_name: com.fdelux.fsdabase
    exe_name: fsdabase-linux-x64

  windows:
    app_name: FSDA Base
    organization: FDelux
    copyright_notice: Copyright ©️ 2026 FDelux. All rights reserved.
    exe_name: fsdabase-win32

  macos:
    app_name: FSDA Base
    bundle_id: com.fdelux.fsdabase
    copyright_notice: Copyright ©️ 2026 FDelux. All rights reserved.
